language: python
python:
  - "3.5"
env:
  global:
    - PYTHONPATH="/home/travis/build/trp07/messages"
install:
  - pip install .
  - pip install pytest-cov pytest-mock coveralls
  - pip install keyrings.alt
  - python3 generate_config.py
  - free -h
  - top -bn1
script: py.test --cov=messages tests/
after_success:
- free -h
- top -bn1
